@extends('layouts.public')
@section('title', 'Acerca de nosotros | Villa Israel')
@section('content')
<section class="institution-hero about-photo"><div class="container"><span class="section-tag light">ACERCA DE NOSOTROS</span><h1>Cuidado cercano.<br><em>Una comunidad más fuerte.</em></h1><p>Conoce la esencia de Villa Israel: personas, compromiso y una forma más sencilla de organizar tu atención.</p><div class="institution-location"><x-icon name="pin"/> {{ config('centro.city') }}</div></div></section>
<section class="section"><div class="container">
@if(config('centro.institutional_copy_is_example'))<p class="institution-example"><x-icon name="help"/> Presentación institucional de ejemplo. La reseña, misión y visión son textos propuestos, pendientes de validación por el centro.</p>@endif
<div class="institution-story"><div><span class="section-tag">NUESTRA ESENCIA</span><h2>La salud empieza<br>con un trato humano.</h2><p class="institution-lead">Imaginamos Villa Israel como ese lugar de confianza al que una familia vuelve para encontrar orientación, escucha y acompañamiento.</p><p>La cercanía también se construye con pequeños detalles: explicar el siguiente paso, respetar el tiempo de cada persona y hacer que una reserva sea fácil de comprender.</p><p>Este espacio digital conecta a pacientes, médicos y administración para que la organización de las citas sea parte del cuidado.</p><a class="text-link dark" href="{{ route('contact') }}">Hablemos de tu próxima visita <span>→</span></a></div><div class="institution-photo"><img src="{{ asset('images/care/consulta-digital.jpg') }}" width="1200" height="800" alt="Profesional de salud y paciente revisando información" loading="lazy"><div><x-icon name="heart"/><span>Personas primero.<strong>Siempre cerca de ti.</strong></span></div></div></div>
<div class="institution-purpose"><article><span class="purpose-icon"><x-icon name="heart"/></span><span class="section-tag">NUESTRA MISIÓN</span><h2>Acompañar con cercanía.</h2><p>{{ config('centro.mission') }}</p></article><article><span class="purpose-icon"><x-icon name="spark"/></span><span class="section-tag">NUESTRA VISIÓN</span><h2>Crecer junto a la comunidad.</h2><p>{{ config('centro.vision') }}</p></article></div>
</div></section>
<section class="institution-values section"><div class="container"><div class="section-heading"><span class="section-tag">LO QUE NOS GUÍA</span><h2>Valores que se sienten<br>en cada encuentro.</h2></div><div class="institution-values-grid">@foreach([['users','Cercanía','Escuchar con atención y explicar con palabras sencillas.'],['clock','Respeto','Valorar el tiempo, la dignidad y las necesidades de cada persona.'],['check-circle','Compromiso','Cuidar los detalles y procurar una atención organizada.']] as [$icon,$title,$text])<article><x-icon :name="$icon"/><h3>{{ $title }}</h3><p>{{ $text }}</p></article>@endforeach</div></div></section>
<section class="section"><div class="container clinic-showcase"><div><span class="section-tag">UN ESPACIO PARA CONOCERNOS</span><h2>Otra perspectiva<br>del cuidado.</h2><p>Explora esta pequeña maqueta interactiva: arrástrala para girar o utiliza los controles inferiores.</p><p class="form-hint">Descubre la fachada principal y la parte posterior del Centro de Salud Villa Israel.</p><a class="button button-dark" href="{{ route('specialties') }}">Conoce las especialidades <x-icon name="arrow"/></a></div><x-clinic-model/></div></section>
<section class="institution-banner"><div class="container"><div><span class="section-tag light">TU PRÓXIMA VISITA</span><h2>Te acompañamos desde el primer paso.</h2></div><a class="button button-light" href="{{ route('booking') }}">Buscar una cita <x-icon name="arrow"/></a></div></section>
@endsection
