@extends('layouts.dashboard')
@section('title','Reportes')
@section('content')
<div class="dashboard-heading"><div><span class="section-tag">INFORMACIÓN PARA DECIDIR</span><h1>La atención en cifras.</h1><p>Consulta las citas por fecha programada, profesional y especialidad.</p></div><a class="button button-dark" href="{{ route('reports',array_merge(request()->query(),['csv'=>1])) }}">↓ Descargar CSV</a></div>
<section class="surface"><form class="filter-toolbar"><label>Desde<input type="date" name="desde" value="{{ $from }}" required></label><label>Hasta<input type="date" name="hasta" value="{{ $to }}" required></label><label>Médico<select name="medico_id"><option value="">Todos</option>@foreach($medicos as $m)<option value="{{ $m->id }}" @selected(request('medico_id')==$m->id)>{{ $m->nombre_completo }}</option>@endforeach</select></label><label>Especialidad<select name="especialidad_id"><option value="">Todas</option>@foreach($especialidades as $e)<option value="{{ $e->id }}" @selected(request('especialidad_id')==$e->id)>{{ $e->nombre }}</option>@endforeach</select></label><label>Estado<select name="estado"><option value="">Todos</option>@foreach(\App\Models\Cita::ESTADOS as $s=>$label)<option value="{{ $s }}" @selected(request('estado')===$s)>{{ $label }}</option>@endforeach</select></label><button class="button button-dark">Aplicar filtros</button></form></section>
<div class="report-grid">@foreach(\App\Models\Cita::ESTADOS as $state=>$label)<article class="surface report-number"><span class="status-badge {{ $state }}">{{ $label }}</span><strong>{{ $counts[$state]??0 }}</strong><div class="report-track"><i style="width:{{ $counts->sum()?round(($counts[$state]??0)/$counts->sum()*100):0 }}%"></i></div></article>@endforeach</div>
<p class="form-hint">{{ $counts->sum() }} citas en el resultado · {{ $reprogramadas }} de ellas se reprogramaron al menos una vez. La reprogramación es un evento del historial y puede coexistir con cualquiera de los estados.</p>
<section class="surface">@include('partials.citas-table')</section>
@endsection
