@extends('layouts.dashboard')
@section('title','Detalle de cita')
@section('content')
<div class="dashboard-heading"><div><a class="back-link" href="{{ route('citas.index') }}">← Volver a citas</a><h1>Tu cita #{{ $cita->id }}</h1><p>Información y seguimiento de la atención.</p></div><span class="status-badge {{ $cita->estado }}">{{ \App\Models\Cita::ESTADOS[$cita->estado] }}</span></div>
<div class="detail-layout"><section class="surface"><span class="section-tag">DETALLE DE RESERVA</span><h2>{{ $cita->especialidad->nombre }}</h2><dl class="detail-list"><div><dt>Paciente</dt><dd>{{ $cita->paciente->nombre_completo }}</dd></div><div><dt>Médico</dt><dd>{{ $cita->medico->nombre_completo }}</dd></div><div><dt>Fecha</dt><dd>{{ $cita->fecha->locale('es')->isoFormat('dddd D [de] MMMM [de] YYYY') }}</dd></div><div><dt>Horario</dt><dd>{{ substr($cita->hora_inicio,0,5) }} — {{ substr($cita->hora_fin,0,5) }}</dd></div><div><dt>Centro</dt><dd>Villa Israel · Cochabamba</dd></div></dl>
@if(auth()->user()->rol==='paciente' && $cita->modificable())<a class="button ghost-button" href="{{ route('citas.reschedule',$cita) }}">Reprogramar cita →</a><form method="post" action="{{ route('citas.state',$cita) }}" class="state-form" data-confirm-message="¿Quieres cancelar esta cita? El horario quedará disponible para otro paciente.">@csrf @method('PATCH')<input type="hidden" name="estado" value="cancelada"><label>Motivo (opcional)<input name="motivo" maxlength="255" placeholder="Cuéntanos el motivo"></label><button class="button danger-button">Cancelar cita</button></form>@endif
@if(auth()->user()->rol!=='paciente' && in_array($cita->estado,['pendiente','confirmada']))<form method="post" action="{{ route('citas.state',$cita) }}" class="state-form" data-confirm-message="¿Confirmas el cambio de estado de esta cita?">@csrf @method('PATCH')<label>Actualizar estado<select name="estado" required><option value="">Selecciona una acción</option>@if(auth()->user()->rol==='administrador')@if($cita->estado==='pendiente')<option value="confirmada">Confirmar</option>@endif<option value="cancelada">Cancelar</option>@endif @if($cita->estado==='confirmada')<option value="atendida">Marcar como atendida</option>@endif<option value="no_asistio">Marcar como no asistió</option></select></label><label>Motivo (opcional)<input name="motivo" maxlength="255"></label><button class="button button-dark">Guardar estado</button></form>@endif
</section><section class="surface"><span class="section-tag">CADA CAMBIO QUEDA REGISTRADO</span><h2>Historial de la cita</h2><ol class="event-timeline">@foreach($cita->historial as $event)<li><strong>{{ ['reserva'=>'Reserva creada','reprogramacion'=>'Cita reprogramada','cancelacion'=>'Cita cancelada','estado'=>'Estado actualizado'][$event->accion]??$event->accion }}</strong><small>{{ $event->created_at->format('d/m/Y H:i') }} · {{ $event->usuario->name }}</small>@if($event->accion==='reprogramacion')<p>{{ $event->fecha_anterior }} {{ substr($event->hora_inicio_anterior,0,5) }} → {{ $event->fecha_nueva }} {{ substr($event->hora_inicio_nueva,0,5) }}</p>@endif<p>{{ \App\Models\Cita::ESTADOS[$event->estado_nuevo]??$event->estado_nuevo }}</p>@if($event->motivo)<p>{{ $event->motivo }}</p>@endif</li>@endforeach</ol></section></div>
@endsection
