<div class="vi-page-heading"><div><div class="vi-eyebrow"><span class="vi-live-dot"></span> ESPACIO DE ADMINISTRACIÓN</div><h1>La jornada de <em>Villa Israel.</em></h1><p>Hola, {{ explode(' ',auth()->user()->name)[0] }}. Aquí empieza la organización de la atención.</p></div><a class="vi-button vi-button-primary" href="{{ route('booking') }}"><x-icon name="plus"/> Nueva cita</a></div>
<div class="vi-date-heading"><span>{{ $date->locale('es')->isoFormat('dddd D [de] MMMM [de] YYYY') }}</span><span>Resumen de la fecha seleccionada</span></div>
<div class="vi-stats-grid">
@foreach([['Citas registradas',$metrics->sum(),'calendar','Todas las atenciones',''],['Por confirmar',$metrics['pendiente'],'clock','Revisa las solicitudes','pendiente'],['Confirmadas',$metrics['confirmada'],'check-circle','Preparadas para la atención','confirmada'],['Atendidas',$metrics['atendida'],'heart','Atenciones completadas','atendida']] as [$name,$value,$icon,$caption,$state])
<a class="vi-stat {{ $loop->first?'vi-stat-featured':'' }}" href="{{ route('citas.index',['fecha'=>$date->toDateString(),'estado'=>$state]) }}"><div><span>{{ $name }}</span><x-icon :name="$icon"/></div><strong>{{ str_pad($value,2,'0',STR_PAD_LEFT) }}</strong><footer><span>{{ $caption }}</span><x-icon name="up-right"/></footer></a>
@endforeach
</div>
<div class="vi-dashboard-grid"><div class="vi-primary-column">@include('partials.dashboard-agenda')
<section class="vi-card"><div class="vi-card-heading"><div><span class="vi-eyebrow">MOVIMIENTO DE LA SEMANA</span><h2>Citas por día</h2></div><a class="vi-small-link" href="{{ route('reports',['desde'=>$week->first()['date']->toDateString(),'hasta'=>$week->last()['date']->toDateString()]) }}">Ver reporte <x-icon name="up-right"/></a></div><div class="vi-chart" aria-label="Citas registradas durante la semana seleccionada">@foreach($week as $day)<a class="vi-chart-column {{ $day['date']->isSameDay($date)?'selected':'' }}" href="{{ route('dashboard.admin',['fecha'=>$day['date']->toDateString()]) }}" aria-label="{{ $day['date']->locale('es')->isoFormat('dddd') }}: {{ $day['count'] }} citas"><strong>{{ $day['count'] }}</strong><span class="vi-chart-track"><i style="--bar:{{ $day['count'] / max(1,$week->max('count')) * 100 }}%"></i></span><small>{{ $day['date']->locale('es')->isoFormat('ddd') }}</small></a>@endforeach</div></section>
</div><aside class="vi-secondary-column">
<section class="vi-network-card"><span class="vi-eyebrow">EL CENTRO EN NÚMEROS</span><div><a href="{{ route('admin.index','pacientes') }}"><strong>{{ $summary['patients'] }}</strong><span>Pacientes registrados <x-icon name="up-right"/></span></a><a href="{{ route('admin.index','medicos') }}"><strong>{{ $summary['doctors'] }}</strong><span>Médicos activos <x-icon name="up-right"/></span></a></div></section>
<section class="vi-card vi-team-card"><div class="vi-card-heading"><div><span class="vi-eyebrow">PERSONAS QUE CUIDAN</span><h2>Equipo médico</h2></div><x-icon name="doctor"/></div>@forelse($team as $member)<a class="vi-team-member" href="{{ route('citas.index',['medico_id'=>$member->id,'fecha'=>$date->toDateString()]) }}"><span class="vi-person-avatar tone-{{ $loop->index%3 }}">{{ mb_substr($member->nombres,0,1) }}{{ mb_substr($member->apellidos,0,1) }}</span><div><strong>{{ $member->nombre_completo }}</strong><small>{{ $member->especialidades->pluck('nombre')->join(' · ') }}</small></div><span class="vi-team-count">{{ $member->citas_count }}<small>citas</small></span></a>@empty<p class="vi-muted vi-padded">Registra al equipo para empezar a organizar sus agendas.</p>@endforelse<a class="vi-card-link" href="{{ route('admin.index','medicos') }}">Gestionar equipo <x-icon name="arrow"/></a></section>
<section class="vi-card vi-activity-card"><div class="vi-card-heading"><div><span class="vi-eyebrow">SEGUIMIENTO</span><h2>Últimos movimientos</h2></div></div><div class="vi-activity-list">@forelse($activity as $event)<a href="{{ route('citas.show',$event->cita_id) }}" class="vi-activity"><span class="vi-activity-dot {{ $event->estado_nuevo }}"></span><div><strong>{{ ['reserva'=>'Nueva reserva','reprogramacion'=>'Cita reprogramada','cancelacion'=>'Cita cancelada','estado'=>'Estado actualizado'][$event->accion]??'Cambio registrado' }}</strong><p>{{ $event->cita?->paciente?->nombre_completo }} · {{ $event->cita?->especialidad?->nombre }}</p><small>{{ $event->created_at->locale('es')->diffForHumans() }}</small></div></a>@empty<div class="vi-quiet-empty"><x-icon name="list"/><p>Los cambios de las citas aparecerán aquí, en orden de llegada.</p></div>@endforelse</div></section>
<section class="vi-community-card"><x-care-photo image="instrumental-medico" class="" alt=""/><a href="{{ route('about') }}"><small>VILLA ISRAEL</small><strong>Cuidamos de<br>nuestra comunidad.</strong><span>Conoce el centro <x-icon name="arrow"/></span></a></section></aside></div>
