@extends('layouts.dashboard', ['role' => 'doctor'])
@section('title', 'Panel médico')
@section('content')
<div class="dashboard-heading"><div><span>JUEVES, 03 DE SEPTIEMBRE</span><h1>Su jornada de hoy.</h1><p>Medicina general · Pediatría</p></div><div class="shift-badge"><i></i><span><small>TURNO ACTIVO</small><strong>07:30 — 13:30</strong></span></div></div>
<div class="metric-row doctor-metrics"><article><span class="metric-icon">□</span><div><small>CITAS DE HOY</small><strong>12</strong><em>3 pendientes</em></div></article><article><span class="metric-icon">✓</span><div><small>ATENDIDAS</small><strong>7</strong><em>58% de la jornada</em></div></article><article><span class="metric-icon">◷</span><div><small>PRÓXIMA CITA</small><strong>10:00</strong><em>En 18 minutos</em></div></article></div>
<div class="doctor-grid"><section class="panel-card agenda-card"><div class="panel-title"><div><span>AGENDA DE HOY</span><h2>Jueves 03</h2></div><div class="date-nav"><button>‹</button><button>Hoy</button><button>›</button></div></div><div class="agenda-list">
    @foreach ([['08:00','Ana Torres','Control general','done'],['08:30','Luis Choque','Dolor abdominal','done'],['09:00','Rosa Méndez','Control pediátrico','done'],['09:30','María Fernández','Consulta general','current'],['10:00','Carlos Vargas','Dolor de cabeza','next'],['10:30','Elena Flores','Control general','next'],['11:00','Disponible','Sin cita asignada','empty']] as $slot)
    <div class="agenda-item {{ $slot[3] }}"><time>{{ $slot[0] }}</time><span class="agenda-line"></span><div class="patient-avatar">{{ $slot[1] === 'Disponible' ? '—' : collect(explode(' ', $slot[1]))->map(fn($p)=>mb_substr($p,0,1))->take(2)->join('') }}</div><div class="agenda-info"><strong>{{ $slot[1] }}</strong><small>{{ $slot[2] }}</small></div><span class="agenda-status">{{ $slot[3] === 'done' ? 'Atendida' : ($slot[3] === 'current' ? 'En atención' : ($slot[3] === 'empty' ? 'Libre' : 'Confirmada')) }}</span><button>•••</button></div>
    @endforeach
</div></section>
<aside class="doctor-side"><section class="next-patient"><span class="next-label">SIGUIENTE PACIENTE</span><div class="next-time"><strong>10:00</strong><span>18 min</span></div><div class="next-person"><span>CV</span><div><h2>Carlos Vargas</h2><p>CI 6543210 · 38 años</p></div></div><dl><div><dt>Motivo</dt><dd>Dolor de cabeza</dd></div><div><dt>Especialidad</dt><dd>Medicina general</dd></div></dl><button class="button button-light button-wide">Ver cita</button></section><section class="panel-card progress-card"><div class="panel-title"><div><span>JORNADA</span><h2>Avance de hoy</h2></div><strong>58%</strong></div><div class="progress-bar"><i style="width:58%"></i></div><p>7 de 12 pacientes atendidos</p></section></aside></div>
@endsection
