@php($appointment=$next->first())
<div class="vi-page-heading"><div><div class="vi-eyebrow"><x-icon name="heart"/> TU ESPACIO PERSONAL</div><h1>Hola, <em>{{ explode(' ',auth()->user()->name)[0] }}.</em></h1><p>Tus citas, tus horarios y un poco más de tranquilidad.</p></div><span class="vi-heading-date">{{ now()->locale('es')->isoFormat('dddd, D [de] MMMM') }}</span></div>
<div class="vi-patient-top"><section class="vi-next-visit">
<div class="vi-visit-topline"><span><span class="vi-live-dot"></span> TU PRÓXIMA VISITA</span>@if($appointment)<span class="vi-visit-code">CITA #{{ str_pad($appointment->id,4,'0',STR_PAD_LEFT) }}</span>@endif</div>
@if($appointment)
<div class="vi-visit-main"><div><span class="status-badge {{ $appointment->estado }}">{{ \App\Models\Cita::ESTADOS[$appointment->estado] }}</span><h2>{{ $appointment->especialidad->nombre }}</h2><p><x-icon name="doctor"/> {{ $appointment->medico->nombre_completo }}</p></div><div class="vi-visit-day"><span>{{ $appointment->fecha->locale('es')->isoFormat('MMM') }}</span><strong>{{ $appointment->fecha->format('d') }}</strong><span>{{ $appointment->fecha->locale('es')->isoFormat('dddd') }}</span></div></div>
<div class="vi-visit-details"><span><x-icon name="clock"/><strong>{{ substr($appointment->hora_inicio,0,5) }} — {{ substr($appointment->hora_fin,0,5) }}</strong><small>Hora de Bolivia</small></span><span><x-icon name="pin"/><strong>Centro de Salud Villa Israel</strong><small>Cochabamba</small></span></div>
<div class="vi-visit-footer"><a class="vi-button vi-button-light" href="{{ route('citas.show',$appointment) }}">Ver mi cita <x-icon name="arrow"/></a><a class="vi-calendar-download" title="Descargar cita. Si cambia el horario, vuelve a añadirla a tu calendario." href="{{ route('citas.calendar',$appointment) }}"><x-icon name="download"/> Añadir a mi calendario</a></div>
@else
<div class="vi-visit-empty"><div class="vi-visit-orbit" aria-hidden="true"><x-icon name="heart"/></div><h2>Hagamos espacio<br>para tu próxima visita.</h2><p>Elige la especialidad y encuentra un horario disponible para ti.</p><a class="vi-button vi-button-light" href="{{ route('booking') }}">Reservar una cita <x-icon name="arrow"/></a></div>
@endif
</section><aside class="vi-patient-side"><a href="{{ route('booking') }}" class="vi-new-visit"><span class="vi-plus-orbit"><x-icon name="plus"/></span><span><strong>Una nueva cita</strong><small>Encuentra tu próximo horario.</small></span><x-icon name="up-right"/></a><div class="vi-patient-numbers"><a href="{{ route('citas.index') }}"><strong>{{ str_pad($summary['upcoming'],2,'0',STR_PAD_LEFT) }}</strong><span>Próximas citas</span><x-icon name="arrow"/></a><a href="{{ route('citas.index',['estado'=>'atendida']) }}"><strong>{{ str_pad($summary['attended'],2,'0',STR_PAD_LEFT) }}</strong><span>Atenciones realizadas</span><x-icon name="arrow"/></a></div><div class="vi-note"><span>UN DETALLE IMPORTANTE</span><p>Puedes cancelar o reprogramar antes del inicio de tu cita. El nuevo horario debe tener al menos una hora de anticipación.</p><a href="{{ route('faq') }}">Resuelve tus dudas <x-icon name="arrow"/></a></div></aside></div>
<div class="vi-dashboard-grid"><div class="vi-primary-column">@include('partials.dashboard-agenda')</div><aside class="vi-secondary-column">
@if($appointment)<section class="vi-card vi-checklist" data-visit-checklist="{{ auth()->id() }}-{{ $appointment->id }}"><x-care-photo image="consulta-digital" class="vi-card-photo" alt="Orientación para una visita médica"/><div class="vi-card-heading"><div><span class="vi-eyebrow">ANTES DE SALIR</span><h2>Prepara tu visita</h2></div><span class="vi-check-progress" data-check-progress>0/3</span></div><p class="vi-check-intro">Un recordatorio personal para el día de tu cita.</p>@foreach(['Llevar mi documento de identidad','Revisar la fecha y la hora','Confirmar la ubicación del centro'] as $item)<label class="vi-check-item"><input type="checkbox" data-visit-check="{{ $loop->index }}"><span class="vi-custom-check"><x-icon name="check"/></span><span>{{ $item }}</span></label>@endforeach<small class="vi-local-note">Tu lista se guarda en este dispositivo.</small></section>@else<section class="vi-card vi-orientation"><x-care-photo image="orientacion-medica" class="vi-card-photo" alt="Conversación de orientación médica"/><x-icon name="pin"/><span class="vi-eyebrow">CERCA DE TI</span><h2>Tu centro de salud,<br>en Cochabamba.</h2><p>Av. Panamericana, sobre Av. General Bartolomé Salomón.</p><a href="{{ route('contact') }}">Ubicación y orientación <x-icon name="arrow"/></a></section>@endif
<section class="vi-card"><div class="vi-card-heading"><div><span class="vi-eyebrow">TU RECORRIDO</span><h2>Últimas citas</h2></div></div>@forelse($recent as $cita)<a class="vi-history-item" href="{{ route('citas.show',$cita) }}"><span class="vi-history-icon"><x-icon name="heart"/></span><div><strong>{{ $cita->especialidad->nombre }}</strong><small>{{ $cita->fecha->format('d/m/Y') }} · {{ \App\Models\Cita::ESTADOS[$cita->estado] }}</small></div><x-icon name="chevron"/></a>@empty<div class="vi-quiet-empty"><x-icon name="calendar"/><p>Aquí podrás volver a consultar tus atenciones anteriores.</p></div>@endforelse<a class="vi-card-link" href="{{ route('citas.index') }}">Consultar mi historial <x-icon name="arrow"/></a></section>
</aside></div>
