@extends('layouts.dashboard', ['role' => 'patient'])
@section('title', 'Panel del paciente')
@section('content')
<div class="dashboard-heading"><div><span>JUEVES, 03 DE SEPTIEMBRE</span><h1>Buenos días, María.</h1><p>Tu próxima cita está confirmada. Aquí tienes todo lo que necesitas.</p></div><a class="button dashboard-primary" href="{{ route('booking') }}">＋ Reservar nueva cita</a></div>
<section class="patient-hero-card"><div class="appointment-date"><span>SEP</span><strong>08</strong><small>MARTES</small></div><div class="appointment-main"><span class="status-pill confirmed"><i></i> CITA CONFIRMADA</span><h2>Medicina general</h2><p>Dr. Daniel Rojas · Consultorio 3</p><div class="appointment-meta"><span><i>◷</i><strong>09:30</strong> — 10:00</span><span><i>⌖</i>Centro de Salud Villa Israel</span></div></div><div class="appointment-actions"><button type="button">Ver detalles</button><button type="button">Reprogramar</button><button class="danger-text" type="button">Cancelar</button></div></section>
<div class="patient-grid"><section class="panel-card quick-card"><div class="panel-title"><div><span>ACCESOS RÁPIDOS</span><h2>¿Qué necesitas hacer?</h2></div></div><div class="quick-grid"><a href="{{ route('booking') }}"><i class="aqua">＋</i><strong>Reservar cita</strong><span>Busca un horario →</span></a><a href="#"><i class="blue">□</i><strong>Mis citas</strong><span>Próximas atenciones →</span></a><a href="#"><i class="yellow">↻</i><strong>Mi historial</strong><span>Revisa citas anteriores →</span></a></div></section>
<section class="panel-card mini-calendar"><div class="panel-title"><div><span>SEPTIEMBRE 2026</span><h2>Tu calendario</h2></div><button>‹</button><button>›</button></div><div class="calendar-days"><b>L</b><b>M</b><b>M</b><b>J</b><b>V</b><b>S</b><b>D</b>@foreach([31,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20] as $day)<span class="{{ $day === 3 ? 'today' : ($day === 8 ? 'has-event' : '') }}">{{ $day }}</span>@endforeach</div><div class="calendar-note"><i></i><span><strong>08 sep · 09:30</strong> Medicina general</span></div></section></div>
<section class="panel-card history-preview"><div class="panel-title"><div><span>ACTIVIDAD RECIENTE</span><h2>Últimas citas</h2></div><a href="#">Ver historial completo →</a></div><div class="compact-table"><div class="table-head"><span>ATENCIÓN</span><span>FECHA</span><span>PROFESIONAL</span><span>ESTADO</span></div><div class="table-row"><span><i class="service-dot aqua"></i><strong>Odontología</strong></span><span>18 ago 2026 · 11:00</span><span>Dra. Laura Méndez</span><span><b class="status-pill attended">Atendida</b></span></div><div class="table-row"><span><i class="service-dot blue"></i><strong>Fisioterapia</strong></span><span>04 ago 2026 · 15:30</span><span>Lic. Carla Soto</span><span><b class="status-pill attended">Atendida</b></span></div></div></section>
@endsection
